// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: pkg/meshtastic/meshtastic.proto

package meshtastic

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The payload types
type PortNum int32

const (
	PortNum_UNKNOWN_APP                 PortNum = 0
	PortNum_TEXT_MESSAGE_APP            PortNum = 1
	PortNum_REMOTE_HARDWARE_APP         PortNum = 2
	PortNum_POSITION_APP                PortNum = 3
	PortNum_NODEINFO_APP                PortNum = 4
	PortNum_ROUTING_APP                 PortNum = 5
	PortNum_ADMIN_APP                   PortNum = 6
	PortNum_TEXT_MESSAGE_COMPRESSED_APP PortNum = 7
	PortNum_WAYPOINT_APP                PortNum = 8
	PortNum_AUDIO_APP                   PortNum = 9
	PortNum_DETECTION_SENSOR_APP        PortNum = 10
	PortNum_REPLY_APP                   PortNum = 32
	PortNum_IP_TUNNEL_APP               PortNum = 33
	PortNum_PAXCOUNTER_APP              PortNum = 34
	PortNum_SERIAL_APP                  PortNum = 64
	PortNum_STORE_FORWARD_APP           PortNum = 65
	PortNum_RANGE_TEST_APP              PortNum = 66
	PortNum_TELEMETRY_APP               PortNum = 67
	PortNum_ZPS_APP                     PortNum = 68
	PortNum_SIMULATOR_APP               PortNum = 69
	PortNum_TRACEROUTE_APP              PortNum = 70
	PortNum_NEIGHBORINFO_APP            PortNum = 71
	PortNum_ATAK_PLUGIN                 PortNum = 72
	PortNum_MAP_REPORT_APP              PortNum = 73
	PortNum_PRIVATE_APP                 PortNum = 256
	PortNum_ATAK_FORWARDER              PortNum = 257
	PortNum_MAX                         PortNum = 511
)

// Enum value maps for PortNum.
var (
	PortNum_name = map[int32]string{
		0:   "UNKNOWN_APP",
		1:   "TEXT_MESSAGE_APP",
		2:   "REMOTE_HARDWARE_APP",
		3:   "POSITION_APP",
		4:   "NODEINFO_APP",
		5:   "ROUTING_APP",
		6:   "ADMIN_APP",
		7:   "TEXT_MESSAGE_COMPRESSED_APP",
		8:   "WAYPOINT_APP",
		9:   "AUDIO_APP",
		10:  "DETECTION_SENSOR_APP",
		32:  "REPLY_APP",
		33:  "IP_TUNNEL_APP",
		34:  "PAXCOUNTER_APP",
		64:  "SERIAL_APP",
		65:  "STORE_FORWARD_APP",
		66:  "RANGE_TEST_APP",
		67:  "TELEMETRY_APP",
		68:  "ZPS_APP",
		69:  "SIMULATOR_APP",
		70:  "TRACEROUTE_APP",
		71:  "NEIGHBORINFO_APP",
		72:  "ATAK_PLUGIN",
		73:  "MAP_REPORT_APP",
		256: "PRIVATE_APP",
		257: "ATAK_FORWARDER",
		511: "MAX",
	}
	PortNum_value = map[string]int32{
		"UNKNOWN_APP":                 0,
		"TEXT_MESSAGE_APP":            1,
		"REMOTE_HARDWARE_APP":         2,
		"POSITION_APP":                3,
		"NODEINFO_APP":                4,
		"ROUTING_APP":                 5,
		"ADMIN_APP":                   6,
		"TEXT_MESSAGE_COMPRESSED_APP": 7,
		"WAYPOINT_APP":                8,
		"AUDIO_APP":                   9,
		"DETECTION_SENSOR_APP":        10,
		"REPLY_APP":                   32,
		"IP_TUNNEL_APP":               33,
		"PAXCOUNTER_APP":              34,
		"SERIAL_APP":                  64,
		"STORE_FORWARD_APP":           65,
		"RANGE_TEST_APP":              66,
		"TELEMETRY_APP":               67,
		"ZPS_APP":                     68,
		"SIMULATOR_APP":               69,
		"TRACEROUTE_APP":              70,
		"NEIGHBORINFO_APP":            71,
		"ATAK_PLUGIN":                 72,
		"MAP_REPORT_APP":              73,
		"PRIVATE_APP":                 256,
		"ATAK_FORWARDER":              257,
		"MAX":                         511,
	}
)

func (x PortNum) Enum() *PortNum {
	p := new(PortNum)
	*p = x
	return p
}

func (x PortNum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PortNum) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_meshtastic_meshtastic_proto_enumTypes[0].Descriptor()
}

func (PortNum) Type() protoreflect.EnumType {
	return &file_pkg_meshtastic_meshtastic_proto_enumTypes[0]
}

func (x PortNum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PortNum.Descriptor instead.
func (PortNum) EnumDescriptor() ([]byte, []int) {
	return file_pkg_meshtastic_meshtastic_proto_rawDescGZIP(), []int{0}
}

// The on-air packets for Meshtastic
type MeshPacket struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The node ID of the sender
	From uint32 `protobuf:"fixed32,1,opt,name=from,proto3" json:"from,omitempty"`
	// The node ID of the destination
	To uint32 `protobuf:"fixed32,2,opt,name=to,proto3" json:"to,omitempty"`
	// The channel this packet was sent on
	Channel uint32 `protobuf:"varint,3,opt,name=channel,proto3" json:"channel,omitempty"`
	// A unique ID for this packet. Always 0 for no-ack packets or non broadcast packets (and therefore
	// not useful). Only useful in ACK packets to allow the sender to identify the packet that was ACK'd.
	Id uint32 `protobuf:"fixed32,6,opt,name=id,proto3" json:"id,omitempty"`
	// The time this message was received by the relay (if any)
	RxTime uint32 `protobuf:"fixed32,7,opt,name=rx_time,json=rxTime,proto3" json:"rx_time,omitempty"`
	// The time this message was received by the local node (if any)
	RxSnr float32 `protobuf:"fixed32,8,opt,name=rx_snr,json=rxSnr,proto3" json:"rx_snr,omitempty"`
	// Received RSSI
	RxRssi int32 `protobuf:"varint,9,opt,name=rx_rssi,json=rxRssi,proto3" json:"rx_rssi,omitempty"`
	// The number of hops remaining
	HopLimit uint32 `protobuf:"varint,10,opt,name=hop_limit,json=hopLimit,proto3" json:"hop_limit,omitempty"`
	// If this is true, we want the recipient to ack this message
	WantAck bool `protobuf:"varint,11,opt,name=want_ack,json=wantAck,proto3" json:"want_ack,omitempty"`
	// This packet was received via MQTT
	ViaMqtt bool `protobuf:"varint,13,opt,name=via_mqtt,json=viaMqtt,proto3" json:"via_mqtt,omitempty"`
	// The original hop limit
	HopStart uint32 `protobuf:"varint,14,opt,name=hop_start,json=hopStart,proto3" json:"hop_start,omitempty"`
	// This packet's public key
	PublicKey []byte `protobuf:"bytes,15,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	// This packet is encrypted with PKI
	PkiEncrypted bool `protobuf:"varint,16,opt,name=pki_encrypted,json=pkiEncrypted,proto3" json:"pki_encrypted,omitempty"`
	// Types that are valid to be assigned to PayloadVariant:
	//
	//	*MeshPacket_Encrypted
	//	*MeshPacket_Decoded
	PayloadVariant isMeshPacket_PayloadVariant `protobuf_oneof:"payload_variant"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MeshPacket) Reset() {
	*x = MeshPacket{}
	mi := &file_pkg_meshtastic_meshtastic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeshPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeshPacket) ProtoMessage() {}

func (x *MeshPacket) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_meshtastic_meshtastic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeshPacket.ProtoReflect.Descriptor instead.
func (*MeshPacket) Descriptor() ([]byte, []int) {
	return file_pkg_meshtastic_meshtastic_proto_rawDescGZIP(), []int{0}
}

func (x *MeshPacket) GetFrom() uint32 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *MeshPacket) GetTo() uint32 {
	if x != nil {
		return x.To
	}
	return 0
}

func (x *MeshPacket) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *MeshPacket) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MeshPacket) GetRxTime() uint32 {
	if x != nil {
		return x.RxTime
	}
	return 0
}

func (x *MeshPacket) GetRxSnr() float32 {
	if x != nil {
		return x.RxSnr
	}
	return 0
}

func (x *MeshPacket) GetRxRssi() int32 {
	if x != nil {
		return x.RxRssi
	}
	return 0
}

func (x *MeshPacket) GetHopLimit() uint32 {
	if x != nil {
		return x.HopLimit
	}
	return 0
}

func (x *MeshPacket) GetWantAck() bool {
	if x != nil {
		return x.WantAck
	}
	return false
}

func (x *MeshPacket) GetViaMqtt() bool {
	if x != nil {
		return x.ViaMqtt
	}
	return false
}

func (x *MeshPacket) GetHopStart() uint32 {
	if x != nil {
		return x.HopStart
	}
	return 0
}

func (x *MeshPacket) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *MeshPacket) GetPkiEncrypted() bool {
	if x != nil {
		return x.PkiEncrypted
	}
	return false
}

func (x *MeshPacket) GetPayloadVariant() isMeshPacket_PayloadVariant {
	if x != nil {
		return x.PayloadVariant
	}
	return nil
}

func (x *MeshPacket) GetEncrypted() []byte {
	if x != nil {
		if x, ok := x.PayloadVariant.(*MeshPacket_Encrypted); ok {
			return x.Encrypted
		}
	}
	return nil
}

func (x *MeshPacket) GetDecoded() *Data {
	if x != nil {
		if x, ok := x.PayloadVariant.(*MeshPacket_Decoded); ok {
			return x.Decoded
		}
	}
	return nil
}

type isMeshPacket_PayloadVariant interface {
	isMeshPacket_PayloadVariant()
}

type MeshPacket_Encrypted struct {
	// The encrypted packet
	Encrypted []byte `protobuf:"bytes,4,opt,name=encrypted,proto3,oneof"`
}

type MeshPacket_Decoded struct {
	// The decrypted packet (only available after decryption)
	Decoded *Data `protobuf:"bytes,5,opt,name=decoded,proto3,oneof"`
}

func (*MeshPacket_Encrypted) isMeshPacket_PayloadVariant() {}

func (*MeshPacket_Decoded) isMeshPacket_PayloadVariant() {}

// The payload portion of a packet, this is the actual message payload.
type Data struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The type of payload
	Portnum PortNum `protobuf:"varint,1,opt,name=portnum,proto3,enum=meshtastic.PortNum" json:"portnum,omitempty"`
	// The payload bytes
	Payload []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	// If true, the recipient should respond
	WantResponse bool `protobuf:"varint,3,opt,name=want_response,json=wantResponse,proto3" json:"want_response,omitempty"`
	// The destination node
	Dest uint32 `protobuf:"fixed32,4,opt,name=dest,proto3" json:"dest,omitempty"`
	// The source node
	Source uint32 `protobuf:"fixed32,5,opt,name=source,proto3" json:"source,omitempty"`
	// A unique ID for this packet
	RequestId uint32 `protobuf:"fixed32,6,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// The ID of the message this is replying to
	ReplyId uint32 `protobuf:"fixed32,7,opt,name=reply_id,json=replyId,proto3" json:"reply_id,omitempty"`
	// An optional emoji to send with the message
	Emoji         uint32 `protobuf:"fixed32,8,opt,name=emoji,proto3" json:"emoji,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_pkg_meshtastic_meshtastic_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_meshtastic_meshtastic_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_pkg_meshtastic_meshtastic_proto_rawDescGZIP(), []int{1}
}

func (x *Data) GetPortnum() PortNum {
	if x != nil {
		return x.Portnum
	}
	return PortNum_UNKNOWN_APP
}

func (x *Data) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Data) GetWantResponse() bool {
	if x != nil {
		return x.WantResponse
	}
	return false
}

func (x *Data) GetDest() uint32 {
	if x != nil {
		return x.Dest
	}
	return 0
}

func (x *Data) GetSource() uint32 {
	if x != nil {
		return x.Source
	}
	return 0
}

func (x *Data) GetRequestId() uint32 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *Data) GetReplyId() uint32 {
	if x != nil {
		return x.ReplyId
	}
	return 0
}

func (x *Data) GetEmoji() uint32 {
	if x != nil {
		return x.Emoji
	}
	return 0
}

// The service envelope wraps the packet with additional metadata
type ServiceEnvelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The actual packet being sent
	Packet *MeshPacket `protobuf:"bytes,1,opt,name=packet,proto3" json:"packet,omitempty"`
	// The channel ID
	ChannelId string `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	// The gateway ID
	GatewayId     string `protobuf:"bytes,3,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceEnvelope) Reset() {
	*x = ServiceEnvelope{}
	mi := &file_pkg_meshtastic_meshtastic_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceEnvelope) ProtoMessage() {}

func (x *ServiceEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_meshtastic_meshtastic_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceEnvelope.ProtoReflect.Descriptor instead.
func (*ServiceEnvelope) Descriptor() ([]byte, []int) {
	return file_pkg_meshtastic_meshtastic_proto_rawDescGZIP(), []int{2}
}

func (x *ServiceEnvelope) GetPacket() *MeshPacket {
	if x != nil {
		return x.Packet
	}
	return nil
}

func (x *ServiceEnvelope) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *ServiceEnvelope) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

var File_pkg_meshtastic_meshtastic_proto protoreflect.FileDescriptor

const file_pkg_meshtastic_meshtastic_proto_rawDesc = "" +
	"\n" +
	"\x1fpkg/meshtastic/meshtastic.proto\x12\n" +
	"meshtastic\"\xb8\x03\n" +
	"\n" +
	"MeshPacket\x12\x12\n" +
	"\x04from\x18\x01 \x01(\aR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\aR\x02to\x12\x18\n" +
	"\achannel\x18\x03 \x01(\rR\achannel\x12\x0e\n" +
	"\x02id\x18\x06 \x01(\aR\x02id\x12\x17\n" +
	"\arx_time\x18\a \x01(\aR\x06rxTime\x12\x15\n" +
	"\x06rx_snr\x18\b \x01(\x02R\x05rxSnr\x12\x17\n" +
	"\arx_rssi\x18\t \x01(\x05R\x06rxRssi\x12\x1b\n" +
	"\thop_limit\x18\n" +
	" \x01(\rR\bhopLimit\x12\x19\n" +
	"\bwant_ack\x18\v \x01(\bR\awantAck\x12\x19\n" +
	"\bvia_mqtt\x18\r \x01(\bR\aviaMqtt\x12\x1b\n" +
	"\thop_start\x18\x0e \x01(\rR\bhopStart\x12\x1d\n" +
	"\n" +
	"public_key\x18\x0f \x01(\fR\tpublicKey\x12#\n" +
	"\rpki_encrypted\x18\x10 \x01(\bR\fpkiEncrypted\x12\x1e\n" +
	"\tencrypted\x18\x04 \x01(\fH\x00R\tencrypted\x12,\n" +
	"\adecoded\x18\x05 \x01(\v2\x10.meshtastic.DataH\x00R\adecodedB\x11\n" +
	"\x0fpayload_variant\"\xf0\x01\n" +
	"\x04Data\x12-\n" +
	"\aportnum\x18\x01 \x01(\x0e2\x13.meshtastic.PortNumR\aportnum\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12#\n" +
	"\rwant_response\x18\x03 \x01(\bR\fwantResponse\x12\x12\n" +
	"\x04dest\x18\x04 \x01(\aR\x04dest\x12\x16\n" +
	"\x06source\x18\x05 \x01(\aR\x06source\x12\x1d\n" +
	"\n" +
	"request_id\x18\x06 \x01(\aR\trequestId\x12\x19\n" +
	"\breply_id\x18\a \x01(\aR\areplyId\x12\x14\n" +
	"\x05emoji\x18\b \x01(\aR\x05emoji\"\x7f\n" +
	"\x0fServiceEnvelope\x12.\n" +
	"\x06packet\x18\x01 \x01(\v2\x16.meshtastic.MeshPacketR\x06packet\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\tR\tchannelId\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x03 \x01(\tR\tgatewayId*\x8d\x04\n" +
	"\aPortNum\x12\x0f\n" +
	"\vUNKNOWN_APP\x10\x00\x12\x14\n" +
	"\x10TEXT_MESSAGE_APP\x10\x01\x12\x17\n" +
	"\x13REMOTE_HARDWARE_APP\x10\x02\x12\x10\n" +
	"\fPOSITION_APP\x10\x03\x12\x10\n" +
	"\fNODEINFO_APP\x10\x04\x12\x0f\n" +
	"\vROUTING_APP\x10\x05\x12\r\n" +
	"\tADMIN_APP\x10\x06\x12\x1f\n" +
	"\x1bTEXT_MESSAGE_COMPRESSED_APP\x10\a\x12\x10\n" +
	"\fWAYPOINT_APP\x10\b\x12\r\n" +
	"\tAUDIO_APP\x10\t\x12\x18\n" +
	"\x14DETECTION_SENSOR_APP\x10\n" +
	"\x12\r\n" +
	"\tREPLY_APP\x10 \x12\x11\n" +
	"\rIP_TUNNEL_APP\x10!\x12\x12\n" +
	"\x0ePAXCOUNTER_APP\x10\"\x12\x0e\n" +
	"\n" +
	"SERIAL_APP\x10@\x12\x15\n" +
	"\x11STORE_FORWARD_APP\x10A\x12\x12\n" +
	"\x0eRANGE_TEST_APP\x10B\x12\x11\n" +
	"\rTELEMETRY_APP\x10C\x12\v\n" +
	"\aZPS_APP\x10D\x12\x11\n" +
	"\rSIMULATOR_APP\x10E\x12\x12\n" +
	"\x0eTRACEROUTE_APP\x10F\x12\x14\n" +
	"\x10NEIGHBORINFO_APP\x10G\x12\x0f\n" +
	"\vATAK_PLUGIN\x10H\x12\x12\n" +
	"\x0eMAP_REPORT_APP\x10I\x12\x10\n" +
	"\vPRIVATE_APP\x10\x80\x02\x12\x13\n" +
	"\x0eATAK_FORWARDER\x10\x81\x02\x12\b\n" +
	"\x03MAX\x10\xff\x03B>Z<github.com/na4ma4/meshtastic-mqtt-bin-to-json/pkg/meshtasticb\x06proto3"

var (
	file_pkg_meshtastic_meshtastic_proto_rawDescOnce sync.Once
	file_pkg_meshtastic_meshtastic_proto_rawDescData []byte
)

func file_pkg_meshtastic_meshtastic_proto_rawDescGZIP() []byte {
	file_pkg_meshtastic_meshtastic_proto_rawDescOnce.Do(func() {
		file_pkg_meshtastic_meshtastic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_meshtastic_meshtastic_proto_rawDesc), len(file_pkg_meshtastic_meshtastic_proto_rawDesc)))
	})
	return file_pkg_meshtastic_meshtastic_proto_rawDescData
}

var file_pkg_meshtastic_meshtastic_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_meshtastic_meshtastic_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_meshtastic_meshtastic_proto_goTypes = []any{
	(PortNum)(0),            // 0: meshtastic.PortNum
	(*MeshPacket)(nil),      // 1: meshtastic.MeshPacket
	(*Data)(nil),            // 2: meshtastic.Data
	(*ServiceEnvelope)(nil), // 3: meshtastic.ServiceEnvelope
}
var file_pkg_meshtastic_meshtastic_proto_depIdxs = []int32{
	2, // 0: meshtastic.MeshPacket.decoded:type_name -> meshtastic.Data
	0, // 1: meshtastic.Data.portnum:type_name -> meshtastic.PortNum
	1, // 2: meshtastic.ServiceEnvelope.packet:type_name -> meshtastic.MeshPacket
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_meshtastic_meshtastic_proto_init() }
func file_pkg_meshtastic_meshtastic_proto_init() {
	if File_pkg_meshtastic_meshtastic_proto != nil {
		return
	}
	file_pkg_meshtastic_meshtastic_proto_msgTypes[0].OneofWrappers = []any{
		(*MeshPacket_Encrypted)(nil),
		(*MeshPacket_Decoded)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_meshtastic_meshtastic_proto_rawDesc), len(file_pkg_meshtastic_meshtastic_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_meshtastic_meshtastic_proto_goTypes,
		DependencyIndexes: file_pkg_meshtastic_meshtastic_proto_depIdxs,
		EnumInfos:         file_pkg_meshtastic_meshtastic_proto_enumTypes,
		MessageInfos:      file_pkg_meshtastic_meshtastic_proto_msgTypes,
	}.Build()
	File_pkg_meshtastic_meshtastic_proto = out.File
	file_pkg_meshtastic_meshtastic_proto_goTypes = nil
	file_pkg_meshtastic_meshtastic_proto_depIdxs = nil
}
